apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-api
spec:
  selector:
    matchLabels:
      app: personal-api
  replicas: 2
  template:
    metadata:
      labels:
        app: personal-api
    spec:
      containers:
        - name: personal-api
          image: sherbolotarbaev/personal-api:latest
          ports:
            - containerPort: 8888
